### ISSUE TITLE
Auto-Completions Aren't Working

### ISSUE THREAD

**Issue by SgtGremulock** [ppalex7/SourcePawnCompletions#10]
Hello,

The auto-completions are not working for me. I know for a fact that I set this up correctly and they are not working. I am currently running Sublime Text 3 (Version 3.1.1, Build 3176).

My directory for my include files:
`D:/SourceMod Projects/Includes`

My SourcePawn Completions.sublime-settings file:
`{
	"include_directory": "D:\\SourceMod Projects\\Includes",
	"bootstrapped": true
}`

The build system works fine, but here is SourcePawn.sublime-build file just in case:
`{
	"cmd": ["D:/SourceMod Projects/spcomp", "-iD:/SourceMod Projects/Includes", "-o$file_path/$file_base_name.smx", "$file"],
	"file_regex": "(.*)\\((\\d+)\\) :",
	"selector": "source.sp"
}`

Thanks,
Grant

**Comment by SgtGremulock** [comment]
If it helps, this is in the console:
`Processing Include File D:\SourceMod Projects\Includes\sourcemod.inc
Processing Include File D:\SourceMod Projects\Includes\core.inc
Processing Include File D:\SourceMod Projects\Includes\version.inc
Exception in thread Thread-2:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\grant\AppData\Roaming\Sublime Text 3\Installed Packages\SourcePawn Completions.sublime-package\SPCompletions.py", line 209, in run
    self.process(file_name, view_buffer)
  File "C:\Users\grant\AppData\Roaming\Sublime Text 3\Installed Packages\SourcePawn Completions.sublime-package\SPCompletions.py", line 219, in process
    self.load_from_file(view_file_name, include, current_node, current_node, base_includes)
  File "C:\Users\grant\AppData\Roaming\Sublime Text 3\Installed Packages\SourcePawn Completions.sublime-package\SPCompletions.py", line 265, in load_from_file
    self.load_from_file(view_file_name, include, node, base_node, base_includes)
  File "C:\Users\grant\AppData\Roaming\Sublime Text 3\Installed Packages\SourcePawn Completions.sublime-package\SPCompletions.py", line 265, in load_from_file
    self.load_from_file(view_file_name, include, node, base_node, base_includes)
  File "C:\Users\grant\AppData\Roaming\Sublime Text 3\Installed Packages\SourcePawn Completions.sublime-package\SPCompletions.py", line 267, in load_from_file
    process_include_file(node)
  File "C:\Users\grant\AppData\Roaming\Sublime Text 3\Installed Packages\SourcePawn Completions.sublime-package\SPCompletions.py", line 365, in process_include_file
    process_lines(file, node)
  File "C:\Users\grant\AppData\Roaming\Sublime Text 3\Installed Packages\SourcePawn Completions.sublime-package\SPCompletions.py", line 383, in process_lines
    if re.search(r'^\s*#pragma deprecated') :
TypeError: search() missing 1 required positional argument: 'string'`

**Comment by SgtGremulock** [comment]
Fixed the issue. I had to comment this out in SPCompletions.py:
`if re.search(r'^\s*#pragma deprecated') : `
